### ISSUE TITLE
Fixed IP/password for get_wl

### ISSUE THREAD

**Issue by salbahra** [littleprojects/Pebble_Opensprinkler#1]
I watch the changes to this repo and also the forum announcements and noticed a possible bug and wanted to report it to you. I noticed the get_wl function has a fixed IP, port and password where the other commands substitute in the IP, port and password. Is this an accident or intentional?

Code: https://github.com/littleprojects/Pebble_Opensprinkler/blob/master/src/app.js#L529

Thanks!

**Comment by littleprojects** [comment]
hey,  thanks, 
this was a bug. a hardcoded url for tests - i fixed it. thanks for the quick response.
